# Generated by Django 4.1.7 on 2023-05-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
    ]
