# Generated by Django 4.1.7 on 2023-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_article_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=100000000000000000, null=True),
        ),
    ]
